/* GENERATED by scripts/gen-blur.mjs -- do not edit by hand.
 *
 * A 12px-wide webp of every raster in public/images/, base64'd, for
 * next/image's `placeholder="blur"`. See the script for why these are
 * generated and committed rather than derived at build time. Re-run it after
 * adding or replacing an image; `node scripts/gen-blur.mjs --check` fails if
 * this file is stale. */
export const blurDataURLs: Record<string, string> = {
  "/images/brainwave-poolside.png":
    "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAgCdASoMAAQAAwBSJZQCdEf/ggeGeiu0AAD7+5mWoneIbH5LEUckvPgv/127ua8AjABG3VCoJyycFpUAAA==",
  "/images/coils-fiber-vs-copper.png":
    "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoMAAQAAwBSJZACdADcAADcAMl0y78mvsE7H9T7FpJIqkcHNVC/dp34OY7qBSLwAAA=",
  "/images/earth-field-aurora.jpg":
    "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoMAAwAAwBSJYwCdAEPAc0SKYAA/vNSz3cd+OVVGGPtQ+ap4cBCuioeKF3bclae10w0YWv/RAAAAA==",
  "/images/earth-magnetic-field-shield.png":
    "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoMAAUAAwBSJbACdAEUo90kwgAA/opR4GNZvRfsU24UlfORDogE6C+7hk2g3HJtB9YSP7zhcAA=",
  "/images/eight-dimensions-wheel.png":
    "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoMAAkAAwBSJYgCdADdQWMfQYAA/vVfIzZIcWK48V80alcRt9Cw4lB1Nmf2nrUeAWbFsCmvgLCC7JLpFd9cXjSYriUSAqMnqX+MC0VAAAA=",
  "/images/eight-dimensions.png":
    "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAgAAwBSJYwCdADdrjifcAAA/vI0jA0umXoudO/lYnNypTEPqDdqe+hv5iMIit4YE0pIDFo8kkOOTVWxYAAA",
  "/images/energetic-vs-tired.png":
    "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoMAAkAAwBSJbACdAYoBVl6u9KwAP6U136f/a7O/fKsV5gbNjR+cMtJje1FqrYpp3FGZkqGAvkrAni1c/PXv95drla7hukAAAA=",
  "/images/essential-air.png":
    "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwAgCdASoMAAoAAwBSJaACdEf/2RQCi5rWyB4AAP5sUeJDvCRyMbc0Scykj8Kcft5g3AA42kV9MwYNQEOLasiAAjZlfXgCQG6dhs04jqd/kPxBGH1CCAl8mgCtfjfU9NrajrL+R5AAAA==",
  "/images/essential-earth-field.jpeg":
    "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoMAAoAAwBSJZgCdADDzoYgAP7pQ1bfZiGFlyax1p3usuy9BTY8e0FVXv6JOVHT4qF2frTTI0uW3bsAAAA=",
  "/images/essential-food.png":
    "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwAgCdASoMAAoAAwBSJbACdDiMwQgjXl7+AAD+m9Sm5BhyHYHULa5POHXLzbrU5JHWOUI7iCqSAOS6CjZcOkVClSHSfNDSw28fNdLVtKEC2jvIBNf/Upg/YjeGya3RsXbF9TJB+XGHnDTyy4O6AAAA",
  "/images/essential-sunshine.png":
    "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAQCdASoMAAsAAwBSJbACdAEOfvhWCwAA9EsljAbTLRMjG5FAJpoqawElzOefVW+b0S+gM9tELJhM9WlTQertQynplVh4IHgFpfsmsYkL5J4gBgK3Z+Z5kHxxrxXCbI68bgAA",
  "/images/essential-water-cutout.webp":
    "data:image/webp;base64,UklGRroAAABXRUJQVlA4WAoAAAAQAAAACwAADAAAQUxQSFMAAAABcFrbthPdWkgNsXBIsJSBpQ4WKo4fhZqccx6VK0j3FhEREwBEw9P7fR6HAND6yIwa1aaBGtJeXWmjTtSoDqUqp1gl5KuADOUQpjSD9FaP28gFAABWUDggQAAAALABAJ0BKgwADQADAFIlnAAC7X8uzpAA/vTdVh5vI9SRmasrsViCBKLsUJRZjb3MiEZKjoAHpIhQPMtvG4dYAAA=",
  "/images/exagon-brain-banner.png":
    "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoMAAUAAwBSJQBOj+ACcIxO5wAA/mqNtoNri+xHHYudkLNuYN6pOcXTmugI7wp/+KSUeuJFJySPwl5EnUncZU0AAAA=",
  "/images/exagon-brain-goggles.png":
    "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoMAAkAAwBSJaQAAlrAKd8AAP74ofl3qqs4zbPiVkbZNwD7511aO4xtDGd+R/az2oDsETIUrwWQAAAA",
  "/images/exagon-fir.png":
    "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoMAAQAAwBSJQAAS4S4wAD+9hftd+2k8u3ybrWjPXvZJSRUG2O1yAAA",
  "/images/exagon-mat.png":
    "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoMAAcAAwBSJaQAAn+2bW42AAD+yp0sMOUNEn6MdlIzrir7a2YI61HzwqG4Fe6k8wdcY76Rz9j9GgAA",
  "/images/exagon-pad.png":
    "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACQAQCdASoMAAQAAwBSJaQAAudVMbgA/vZggIHy1/8+QEJ/v5mmExgYhU8/SrNocAA=",
  "/images/exagon-sense.png":
    "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoMAAkAAwBSJaACdAEVjZRua4AA/ubyTiBzFQ2Q8p3oZxZyHr5vTkHmbohKPjYe7M00gXnII/m4J0zcUctscP0mstfBhkIwiPw8W9W04AFDYyqAAAA=",
  "/images/exagon-split-mode.png":
    "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACQAQCdASoMAAcAAwBSJbACdABoWUAA8j4LmnwOl+FuF4+KRvwDgj8ZV97CPk6o7rk0AA==",
  "/images/exagon-spot.png":
    "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoMAAQAAwBSJaQAAudQDTgAAP71PcWOGMBQgRQ+umhPI30eN7s1kgAA",
  "/images/hero-mat-fireplace.png":
    "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoMAAYAAwBSJYgCdAEUu+J1qHzAAP6J60XnXOOw0TUUoC8YEtoK3fjMr6oX95L3VwojV27Ygk3XCunIF8kUMZ1G23KouMkCUyEgUAAA",
  "/images/holistic-balance-stones.png":
    "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoMAAgAAwBSJbACdADZlhSAAP3joUcdM7x4FkFUvBxQxedAJ20xvDULXMhrUnAiHzJ+6+LnAZPUFJdkXijOU8FXjulfiAfXXcTlD5gA",
  "/images/holistic-mind-body-spirit.png":
    "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoMAAoAAwBSJZwAAlJ0aIYAAP7v/POaRlwVrAj/j/85kjBf6LsguuJVU807Y/3LKroib7JXajFy5ueFB6dW1nNTs5tosBWBAAA=",
  "/images/holistic-six-dimensions-wheel.png":
    "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADQAgCdASoMAAsAAwBSJbACdH8D2MCIWJz48LZkKr8AAP7rxdosNowT88NRdDnIc9tFrASyRyEtb1qsvSGWUA4hNPWFs+9+ng3r9zza7Ugr1Zx+oopUWGvozWeN6RZr2+/gVdoR9GNybUL0OTRhtNld2qfDNBVmNJYtfm80EiGIu2OK1bkAAA==",
  "/images/horse-area-applicator.png":
    "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoMAAcAAwBSJYgAAsfy5+kQAP7qSupL1fLYgT3Gx9q/DhImDJNzFI6/YOcy69Q3Jrc79iMBCQ8pcAAA",
  "/images/horse-leg-applicator-2026.png":
    "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoMAAcAAwBSJYgAAqHhBPHcAAD+6krqlHXLtD/zOPjs6zJ9oBNL0D5J4iUm5pGhfnHfsRgISHlLgAAA",
  "/images/imrs-connector-box.png":
    "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAcAAwBSJaQAAubM46CPAAD+m7EW5r+5mruZgcG2TicQqGqOJuo+1XX8Cc0MhHHgQAAA",
  "/images/imrs-control-panel.png":
    "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoMAAcAAwBSJaQAAxOifqoZGAAA/uiUMLceZPZ3/wiSOFkonmDR81fDrR0GC7VNpkBCUfvjFMqmelATC7hHTFSKExuAAA==",
  "/images/imrs-fauna-horses.png":
    "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAMAAwBSJQBOgCFsLgw46AD84je1Vj+ZaHE6oyRcl04sLfNA0DYoTa+bWepwrsIxYQAA",
  "/images/imrs-model-3.png":
    "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoMAAcAAwBSJYgCdADcq6KGcAD+0i/XNRmp302mF87T3U5fSW0vCKJdBkqfXJfIiHnwOR6K4LXAEXmWzFAHoOPnrCAAAA==",
  "/images/imrs-prime-modes.jpg":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoMAAcAAwBSJbACdGuAt/8DcMEyYAD+6JR4anih+yd+k4FmcRrhJvwmsfE7+QH1EuKIhBKQcVXE5tplLj3okDON2tbc7fgOAYxXwMfJvkAAAA==",
  "/images/magnet-poles.png":
    "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQAQCdASoMAAkAAwBSJQBOgBsBaoAA/vCP4M2ZO+vpVbm3nI+GMMk3yEP+3zIFzk6VO0QRuSHY7ChYje8v3m+acsIKZgG053ohpIpRXs2/4gT2cGwBNgAA",
  "/images/magnetic-field-weakening.webp":
    "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAAgAAwBSJZgCdAD6Iy7unAAA/vNgtc7e5nIMdOmvdI3imalVpFfWIE1WTzlpX/LVjH0XDzpD3zwZeqj4AA==",
  "/images/mental-training.png":
    "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoMAAkAAwBSJZACdADp3YwUsAAA/vipxotCin3jy8ic8a+1DWGCN1F92zBnrBD+/o8kArXynK7GHxrxhwBbpJAPZ6KygMgAAAA=",
  "/images/organ-functions.webp":
    "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAQCdASoMAAwAAwBSJZwAApKc60AA/vdg2hW4NzmqUTSjnylMz0ohKwIJ7CIXmu5VwcQeQo+jWMEUTNgJsAAA",
  "/images/passive-warmup.png":
    "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoMAAsAAwBSJQBOj+AC4Y631wAA/vqOxMf0Y4qQO4fEenpu+zwTa6dlZ9yeJ7+vuxL6YSf4m9cbikXmrYeZbmLMy7DC2X3fkroC4A/gAAA=",
  "/images/pemf-dog-pad.png":
    "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoMAAcAAwBSJYwAAxS3DqrLgAD+76K8E1rUzx92JsdrPtvA3Pd+W+h2mkTtgs/uVeyzE+4lr0GF9zuRmiygXoLwAAA=",
  "/images/pemf-earth-field.png":
    "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoMAAUAAwBSJQBOgBugjKSAAP7sC37ieKxWlY1ExoMGIzvTXLH0UGBuneTQAA==",
  "/images/pemf-mimics-earth-field.png":
    "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoMAAYAAwBSJYwCdADczHkgAP7urz6rDNBKkeCZ5LLWz+ooWGPwq6MwQufuV7lhzXwgm7DfFwAAAA==",
  "/images/performance.png":
    "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwAgCdASoMAAsAAwBSJZACdAYtBa7DIF68kAD++u+jbknQBELzULP1/13rTLbMoptDfMPxpoYfUUgIPVsdtSP0xXkfriOH86+ft3jlO7ZClgh62licyrbUNZh33C/AHpHVm+i5oG8ZaPy67W3qj68dMbEBVaegAAA=",
  "/images/pets-group.png":
    "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoMAAkAAwBSJQBOgMV4zynZhgvCcAD+9WD7xzTri+4Jn3fNeOfdDfhm4BjneOk+JFi+rfvE4Pxa9a64pCnMlfNe001EjviLf7jk4NWKmMUz0+Mwv+YUUxAA",
  "/images/rejuvenation.png":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoMAAsAAwBSJZQC7AYpbnMzYLi8gAD++WN5aKhQ/Vh2PTb5eSKoTZopL7apu91XmfRmeDD8zPau7Bpqzq4VeCLGHR/RS29rItBfS7y1UG3cCr8sfjP5kBxaYAAAAA==",
  "/images/relax-poolside.jpg":
    "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoMAAcAAwBSJZgCdAELVKObWBcAAPZneA95uDurAz25K1h5u1NbbWW8OPNg6RAwZg+LLMXgOuTZi8ivkZR6esEwc2Tx832OnSkAAA==",
  "/images/show-animals.png":
    "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoMAAkAAwBSJZAC7AEf58ne2RsEAP744tLXAEDwdCaD4mzvgnib9Q7nojBo9FFBvYP8Btr0Y3ZH/oD4IJkY0dnmlHeEU0kdt84AAA==",
  "/images/sleep-mat-tablet.png":
    "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoMAAcAAwBSJYgCdH8AGMDiZ183gAD+yPteQcicCJpb73oMwQc3lXIQ9wJC523OCOYAxbKUPdffc48fZNUQ1d0YhA/D7/bIHjt2wAAA",
  "/images/smart-pulser-set.png":
    "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoMAAcAAwBSJZwAD4SQ/EQv36M4AAD+912LGfYe0pdxcQ6Zzf5W8oklxRAOfdKoCdCXABeDosSqXXHfAmwTjwJ2hicvNAAA",
  "/images/sources-of-radiation-hires.jpg":
    "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoMAAgAAwBSJYwAAjp17xsAAP71SZgA0UcCQ3Zz8M/HemfB4Aq2shV59AN2/5oDPAc7dCeShy+tyMe24AAAAA==",
  "/images/stress-gauge.png":
    "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAQCdASoMAAkAAwBSJaACdADaNHXaAAD++ZYolaJDUSHu87rgjvv15spoF7A9i3pct5gLvnVMSj4sEO463vYqHLN5hvlIBs+eD9Hy/yT2JTvl8Jmq4HRd1ZdcEAAA",
  "/images/wechat-qr.png":
    "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoMAAwAAwBSJaQAGyA4JEIzAvJqgAD+t+8a17o9jeeboP/xEHyOE1w/mvU7HtzplsqoThMU1ypqwybbi9Yg5LCgs1QwF5ExZ543Y4AA",
  "/images/wellness-practices.png":
    "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoMAA0AAwBSJZQAAxZnHcogIkgAAP71N1oc72WcrVHXSWbsMtWrY5NrUA7yXQuhHC21TgJpGHIIGbJIdX6HFfZXTujkubGS42TGDfJ7w8SyZTGoAAA=",
};

/** Placeholder props for a next/image, spread at the call site:
 *
 *      <Image src={img.src} {...blurFor(img.src)} ... />
 *
 *  Returns nothing for an SVG or for any image with no generated placeholder,
 *  so a call site never has to know which is which and a missing entry
 *  degrades to today's behaviour rather than throwing. */
export function blurFor(src: string) {
  const blurDataURL = blurDataURLs[src];
  return blurDataURL ? ({ placeholder: "blur", blurDataURL } as const) : {};
}
