// Generates the blur-up placeholders next/image shows while a lazy image
// loads, and writes them to lib/content/blur.ts.
//
//   node scripts/gen-blur.mjs            regenerate lib/content/blur.ts
//   node scripts/gen-blur.mjs --check    fail if it is out of date (CI/pre-commit)
//
// Why this exists at all: next/image can only derive a blurDataURL by itself
// from a statically imported image. Every image on this site is referenced by
// string src through lib/content/images.ts -- which is deliberate, it is what
// keeps alt text and provenance in one place -- so the placeholders have to be
// produced here instead. Without them a below-the-fold image pops in from
// blank, which reads as a stall rather than as loading.
//
// The output is committed. It is derived from files in public/images/, so it
// could be built at build time, but committing it keeps `next build` free of a
// sharp dependency and makes the diff visible when an image is swapped -- which
// on this site happens often. Re-run this after adding or replacing any image;
// --check is there so a stale file is caught rather than silently shipped.
//
// SVGs are skipped. They are vector, already small, and served with
// `unoptimized`, so a raster placeholder for one would be both pointless and
// larger than the thing it stands in for.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import sharp from "sharp";

const DIR = "public/images";
const OUT = "lib/content/blur.ts";

// 12px wide is the whole trick: large enough to carry the image's colour
// layout, small enough that the base64 stays a few hundred bytes and can sit
// inline in the HTML without being worth lazy-loading itself. webp because it
// beats jpeg at this size and every browser that supports next/image's
// placeholder supports it.
const WIDTH = 12;
const QUALITY = 45;

const RASTER = /\.(png|jpe?g|webp)$/i;

async function build() {
  const files = readdirSync(DIR).filter((f) => RASTER.test(f)).sort();
  const entries = [];
  for (const file of files) {
    const data = await sharp(join(DIR, file))
      .resize(WIDTH, null, { fit: "inside" })
      .webp({ quality: QUALITY })
      .toBuffer();
    entries.push([`/images/${file}`, `data:image/webp;base64,${data.toString("base64")}`]);
  }
  const body = entries.map(([src, uri]) => `  "${src}":\n    "${uri}",`).join("\n");
  return `/* GENERATED by scripts/gen-blur.mjs -- do not edit by hand.
 *
 * A ${WIDTH}px-wide webp of every raster in public/images/, base64'd, for
 * next/image's \`placeholder="blur"\`. See the script for why these are
 * generated and committed rather than derived at build time. Re-run it after
 * adding or replacing an image; \`node scripts/gen-blur.mjs --check\` fails if
 * this file is stale. */
export const blurDataURLs: Record<string, string> = {
${body}
};

/** Placeholder props for a next/image, spread at the call site:
 *
 *      <Image src={img.src} {...blurFor(img.src)} ... />
 *
 *  Returns nothing for an SVG or for any image with no generated placeholder,
 *  so a call site never has to know which is which and a missing entry
 *  degrades to today's behaviour rather than throwing. */
export function blurFor(src: string) {
  const blurDataURL = blurDataURLs[src];
  return blurDataURL ? ({ placeholder: "blur", blurDataURL } as const) : {};
}
`;
}

const generated = await build();
if (process.argv.includes("--check")) {
  const current = readFileSync(OUT, "utf8");
  if (current !== generated) {
    console.error(
      `\n  FAIL ${OUT} is out of date. Run: node scripts/gen-blur.mjs\n`
    );
    process.exit(1);
  }
  console.log(`\n  ok   ${OUT} is up to date\n`);
} else {
  writeFileSync(OUT, generated);
  const count = (generated.match(/data:image\/webp/g) || []).length;
  console.log(`\n  wrote ${OUT} -- ${count} placeholders\n`);
}
